name: watch
description: "movie app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  internet_connection_checker: ^1.0.0+1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.2
  flutter_phoenix: ^1.1.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.1.5 
  freezed: ^2.5.7
flutter:
  uses-material-design: true
  assets:
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/loading.json
    - assets/json/success.json
    - assets/translations/ar.json
    - assets/translations/en.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
